name: Build, Push, and Deploy to Render
on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build the project
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ashik47/c-backend:latest .

    - name: Push Docker image
      run: docker push ashik47/c-backend:latest

    - name: Trigger Render Deployment
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
